### PR TITLE
Add Poloniex to official markets

### PR DESCRIPTION
**Pull request by gilrosenthal**
Using [the Poloniex API](https://poloniex.com/support/api/), I added another market to the data sources with their data. I also removed them from the cryptowatch API source, so that we don't get conflicting data.
Cheers!

### CODE REVIEW

**Comment by Primly** [comment]
quick question, whats the advantage over pulling data directly from Poloniex API versus relying on Cryptowatch? Thanks!

**Comment by gilrosenthal** [comment]
According to https://cryptowat.ch/docs/api#prices, they can be outdated by a few seconds, and if this is going to be turned into a trading bot, real-time quotes are insanely important, can't hurt!

**Comment by Primly** [comment]
I was thinking it must be something like that...good choice!

**Comment by manu354** [comment]
Thanks :) Code looks perfect! Will merge now.

**Comment by manu354** [comment]
Just looked at the results from poloniex and realised that cryptowatch didn't list alot of the coins for poloniex so it was actually very good to use its own API. I will try do this for all the coins listed on cryptowatch and stop using the cryptowatch API.

**Comment by artursapek** [comment]
@gilrosenthal @Primly the cryptowatch API is only a few sec out of date on the aggregate endpoint https://api.cryptowat.ch/markets/prices. Any market specific endpoint like https://api.cryptowat.ch/markets/poloniex/ethbtc/price is updated in real time.

**Pull request merged**
